export enum UsersQueueMessageTypes {
  CREATE_USER = 'CREATE_USER',
  FETCH_USERS = "FETCH_USERS",
  FETCH_USER_BY_ID = "FETCH_USER_BY_ID",
  FETCH_USER_BY_EMAIL = "FETCH_USER_BY_EMAIL"
}


export enum UsersQueueEventTypes {
  USER_CREATED = 'USER_CREATED',
  USERS_FETCHED = "USERS_FETCHED",
  USER_FETCHED_BY_ID = "USER_FETCHED_BY_ID",
  USER_FETCHED_BY_EMAIL = "USER_FETCHED_BY_EMAIL",
  USER_CREATE_EXCEPTION = "USER_CREATE_EXCEPTION"
}
