export enum ContentTypes {
  JSON = 'application/json',
  TEXT = 'text/plain',
  STREAM = 'application/octet-stream'
}

export enum RoutingKeys {
  MESSAGE = 'MESSAGE', // instruction to do something
  EVENT = 'EVENT', // results of instruction
}








export enum MicroservicesQueues {
  EMAILS = "EMAILS",

  USER_MESSAGES = 'USER_MESSAGES_QUEUE',
  USER_EVENTS = 'USER_EVENTS_QUEUE',

  AUTHORITY_MESSAGES = "AUTHORITY_MESSAGES_QUEUE",
  AUTHORITY_EVENTS = "AUTHORITY_EVENTS_QUEUE",

  CLIENT_MESSAGES = "CLIENT_MESSAGES_QUEUE",
  CLIENT_EVENTS = "CLIENT_EVENTS_QUEUE",

  ASSET_MESSAGES = "ASSET_MESSAGES_QUEUE",
  ASSET_EVENTS = "ASSET_EVENTS_QUEUE",
}


export enum MicroservicesExchanges {
  USER_MESSAGES = 'USER_MESSAGES_EXCHANGE',
  USER_EVENTS = 'USER_EVENTS_EXCHANGE',

  AUTHORITY_MESSAGES = "AUTHORITY_MESSAGES_EXCHANGE",
  AUTHORITY_EVENTS = "AUTHORITY_EVENTS_EXCHANGE",

  CLIENT_MESSAGES = "CLIENT_MESSAGES_EXCHANGE",
  CLIENT_EVENTS = "CLIENT_EVENTS_EXCHANGE",

  ASSET_MESSAGES = "ASSET_MESSAGES_EXCHANGE",
  ASSET_EVENTS = "ASSET_EVENTS_EXCHANGE",
}
