export enum AssetsQueueMessageTypes {
  CREATE_ASSET = 'CREATE_ASSET',
  UPDATE_ASSET = "UPDATE_ASSET",
  DELETE_ASSET = "DELETE_ASSET",
  FETCH_ASSETS_BY_AUTHORITY_ID = "FETCH_ASSETS_BY_AUTHORITY_ID",
  FETCH_ASSETS_BY_AUTHORITY_ID_PAGINATE = "FETCH_ASSETS_BY_AUTHORITY_ID_PAGINATE",
  FETCH_ASSET_BY_ID = "FETCH_ASSET_BY_ID",
  FETCH_ASSET_BY_UUID = "FETCH_ASSET_BY_UUID"
}




export enum AssetsQueueEventTypes {
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = "ASSET_UPDATED",
  ASSET_DELETED = "ASSET_DELETED",
  FETCHED_ASSETS_BY_AUTHORITY_ID = "FETCHED_ASSETS_BY_AUTHORITY_ID",
  FETCHED_ASSETS_BY_AUTHORITY_ID_PAGINATE = "FETCHED_ASSETS_BY_AUTHORITY_ID_PAGINATE",
  FETCHED_ASSET_BY_ID = "FETCHED_ASSET_BY_ID",
  FETCHED_ASSET_BY_UUID = "FETCHED_ASSET_BY_UUID"
}
