export enum AuthoritiesQueueMessageTypes {
  CREATE_AUTHORITY = 'CREATE_AUTHORITY',
  UPDATE_AUTHORITY = "UPDATE_AUTHORITY",
  FETCH_AUTHORITIES = "FETCH_AUTHORITIES",
  FETCH_AUTHORITY_BY_ID = "FETCH_AUTHORITY_BY_ID",
  FETCH_AUTHORITY_BY_UUID = "FETCH_AUTHORITY_BY_UUID",
  FETCH_AUTHORITY_BY_EMAIL = "FETCH_AUTHORITY_BY_EMAIL",
  LOGIN_AUTHORITY = "LOGIN_AUTHORITY",
  DELETE_AUTHORITY = "DELETE_AUTHORITY"
}




export enum AuthoritiesQueueEventTypes {
  AUTHORITY_LOGGED_IN = 'AUTHORITY_LOGGED_IN',
  AUTHORITY_CREATED = 'AUTHORITY_CREATED',
  AUTHORITY_UPDATED = 'AUTHORITY_UPDATED',
  AUTHORITY_DELETED = 'AUTHORITY_DELETED',
  AUTHORITIES_FETCHED = "AUTHORITIES_FETCHED",
  AUTHORITY_FETCHED_BY_ID = "AUTHORITY_FETCHED_BY_ID",
  AUTHORITY_FETCHED_BY_UUID = "AUTHORITY_FETCHED_BY_UUID",
  AUTHORITY_FETCHED_BY_EMAIL = "AUTHORITY_FETCHED_BY_EMAIL",
  
  AUTHORITY_CREATE_EXCEPTION = "AUTHORITY_CREATE_EXCEPTION",
  AUTHORITY_LOGIN_EXCEPTION = "AUTHORITY_LOGIN_EXCEPTION"
}
