export enum ClientsQueueMessageTypes {
  ADD_CLIENT = 'ADD_CLIENT',
  
  FETCH_CLIENTS_BY_AUTHORITY_ID = "FETCH_CLIENTS_BY_AUTHORITY_ID",
  FETCH_CLIENTS_BY_AUTHORITY_ID_PAGINATE = "FETCH_CLIENTS_BY_AUTHORITY_ID_PAGINATE",
  FETCH_CLIENTS_BY_USER_ID = "FETCH_CLIENTS_BY_USER_ID",
  FETCH_CLIENTS_BY_USER_ID_PAGINATE = "FETCH_CLIENTS_BY_USER_ID_PAGINATE",
  FETCH_CLIENT_BY_ID = "FETCH_CLIENT_BY_ID",
  FETCH_CLIENT_BY_UUID = "FETCH_CLIENT_BY_UUID"
}




export enum ClientsQueueEventTypes {
  CLIENT_ADDED = 'CLIENT_ADDED',

  FETCHED_CLIENTS_BY_AUTHORITY_ID = "FETCHED_CLIENTS_BY_AUTHORITY_ID",
  FETCHED_CLIENTS_BY_AUTHORITY_ID_PAGINATE = "FETCHED_CLIENTS_BY_AUTHORITY_ID_PAGINATE",
  FETCHED_CLIENTS_BY_USER_ID = "FETCHED_CLIENTS_BY_USER_ID",
  FETCHED_CLIENTS_BY_USER_ID_PAGINATE = "FETCHED_CLIENTS_BY_USER_ID_PAGINATE",
  FETCHED_CLIENT_BY_ID = "FETCHED_CLIENT_BY_ID",
  FETCHED_CLIENT_BY_UUID = "FETCHED_CLIENT_BY_UUID"
}
