export enum EmailsQueueMessageTypes {
  
}




export enum EmailsQueueEventTypes {
  USER_WELCOME_EMAIL_SENT = "USER_WELCOME_EMAIL_SENT",
  AUTHORITY_WELCOME_EMAIL_SENT = "AUTHORITY_WELCOME_EMAIL_SENT",

  USER_GOODBYE_EMAIL_SENT = "USER_GOODBYE_EMAIL_SENT",
  AUTHORITY_GOODBYE_EMAIL_SENT = "AUTHORITY_GOODBYE_EMAIL_SENT",
}
