export enum EmailsQueueMessageTypes {
  SEND_EMAIL = "SEND_EMAIL",

  RESET_USER_PASSWORD = "RESET_USER_PASSWORD",
  RESET_AUTHORITY_PASSWORD = "RESET_AUTHORITY_PASSWORD",
}




export enum EmailsQueueEventTypes {
  SENT_EMAIL = "SENT_EMAIL",

  USER_WELCOME_EMAIL_SENT = "USER_WELCOME_EMAIL_SENT",
  AUTHORITY_WELCOME_EMAIL_SENT = "AUTHORITY_WELCOME_EMAIL_SENT",

  USER_GOODBYE_EMAIL_SENT = "USER_GOODBYE_EMAIL_SENT",
  AUTHORITY_GOODBYE_EMAIL_SENT = "AUTHORITY_GOODBYE_EMAIL_SENT",

  RESETTED_USER_PASSWORD = "RESETTED_USER_PASSWORD",
  RESETTED_AUTHORITY_PASSWORD = "RESETTED_AUTHORITY_PASSWORD",
}
