export enum NotificationsQueueMessageTypes {
  FETCH_USER_NOTIFICATIONS_LAST_OPENED = "FETCH_USER_NOTIFICATIONS_LAST_OPENED",
  FETCH_USER_NOTIFICATIONS = "FETCH_USER_NOTIFICATIONS",
  FETCH_USER_NOTIFICATIONS_PAGINATE = "FETCH_USER_NOTIFICATIONS_PAGINATE",
  CREATE_USER_NOTIFICATION = "CREATE_USER_NOTIFICATION",

  FETCH_AUTHORITY_NOTIFICATIONS_LAST_OPENED = "FETCH_AUTHORITY_NOTIFICATIONS_LAST_OPENED",
  FETCH_AUTHORITY_NOTIFICATIONS = "FETCH_AUTHORITY_NOTIFICATIONS",
  FETCH_AUTHORITY_NOTIFICATIONS_PAGINATE = "FETCH_AUTHORITY_NOTIFICATIONS_PAGINATE",
  CREATE_AUTHORITY_NOTIFICATION = "CREATE_AUTHORITY_NOTIFICATION",
}




export enum NotificationsQueueEventTypes {
  FETCHED_USER_NOTIFICATIONS_LAST_OPENED = "FETCHED_USER_NOTIFICATIONS_LAST_OPENED",
  FETCHED_USER_NOTIFICATIONS = "FETCHED_USER_NOTIFICATIONS",
  FETCHED_USER_NOTIFICATIONS_PAGINATE = "FETCHED_USER_NOTIFICATIONS_PAGINATE",
  CREATED_USER_NOTIFICATION = "CREATED_USER_NOTIFICATION",

  FETCHED_AUTHORITY_NOTIFICATIONS_LAST_OPENED = "FETCHED_AUTHORITY_NOTIFICATIONS_LAST_OPENED",
  FETCHED_AUTHORITY_NOTIFICATIONS = "FETCHED_AUTHORITY_NOTIFICATIONS",
  FETCHED_AUTHORITY_NOTIFICATIONS_PAGINATE = "FETCHED_AUTHORITY_NOTIFICATIONS_PAGINATE",
  CREATED_AUTHORITY_NOTIFICATION = "CREATED_AUTHORITY_NOTIFICATION",
}
