export enum UsersQueueMessageTypes {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = "UPDATE_USER",
  FETCH_USERS = "FETCH_USERS",
  FETCH_USER_BY_ID = "FETCH_USER_BY_ID",
  FETCH_USER_BY_UUID = "FETCH_USER_BY_UUID",
  FETCH_USER_BY_EMAIL = "FETCH_USER_BY_EMAIL",
  LOGIN_USER = "LOGIN_USER",
  DELETE_USER = "DELETE_USER"
}




export enum UsersQueueEventTypes {
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USERS_FETCHED = "USERS_FETCHED",
  USER_FETCHED_BY_ID = "USER_FETCHED_BY_ID",
  USER_FETCHED_BY_UUID = "USER_FETCHED_BY_UUID",
  USER_FETCHED_BY_EMAIL = "USER_FETCHED_BY_EMAIL",
  
  USER_CREATE_EXCEPTION = "USER_CREATE_EXCEPTION",
  USER_LOGIN_EXCEPTION = "USER_LOGIN_EXCEPTION"
}
